insert into Towns (town_id, name, state_id) values (1, 'Wanmingang', 76);
insert into Towns (town_id, name, state_id) values (2, 'Antofagasta', 102);
insert into Towns (town_id, name, state_id) values (3, 'Jinhua', 107);
insert into Towns (town_id, name, state_id) values (4, 'Kishorganj', 107);
insert into Towns (town_id, name, state_id) values (5, 'Quanjiang', 107);
insert into Towns (town_id, name, state_id) values (6, 'Cisitu', 113);
insert into Towns (town_id, name, state_id) values (7, 'Yeniköy', 92);
insert into Towns (town_id, name, state_id) values (8, 'Miyako', 180);
insert into Towns (town_id, name, state_id) values (9, 'Helmsange', 115);
insert into Towns (town_id, name, state_id) values (10, 'Xekar', 65);
insert into Towns (town_id, name, state_id) values (11, 'Galátsi', 60);
insert into Towns (town_id, name, state_id) values (12, 'Guanzhuang', 180);
insert into Towns (town_id, name, state_id) values (13, 'Fangcun', 89);
insert into Towns (town_id, name, state_id) values (14, 'Eldoret', 193);
insert into Towns (town_id, name, state_id) values (15, 'Rogóźno', 56);
insert into Towns (town_id, name, state_id) values (16, 'Sanshui', 6);
insert into Towns (town_id, name, state_id) values (17, 'Nugas', 125);
insert into Towns (town_id, name, state_id) values (18, 'Cova Figueira', 173);
insert into Towns (town_id, name, state_id) values (19, 'Novaya Usman’', 97);
insert into Towns (town_id, name, state_id) values (20, 'Yershov', 66);
insert into Towns (town_id, name, state_id) values (21, 'Watubuku', 169);
insert into Towns (town_id, name, state_id) values (22, 'Caen', 4);
insert into Towns (town_id, name, state_id) values (23, 'Haibara', 102);
insert into Towns (town_id, name, state_id) values (24, 'Kungsör', 159);
insert into Towns (town_id, name, state_id) values (25, 'Buenos Aires', 165);
insert into Towns (town_id, name, state_id) values (26, 'Maurole', 151);
insert into Towns (town_id, name, state_id) values (27, 'Čajniče', 169);
insert into Towns (town_id, name, state_id) values (28, 'Stalowa Wola', 115);
insert into Towns (town_id, name, state_id) values (29, 'Smętowo Graniczne', 75);
insert into Towns (town_id, name, state_id) values (30, 'Viga', 108);
insert into Towns (town_id, name, state_id) values (31, 'Stockholm', 189);
insert into Towns (town_id, name, state_id) values (32, 'Nariño', 197);
insert into Towns (town_id, name, state_id) values (33, 'Daigo', 197);
insert into Towns (town_id, name, state_id) values (34, 'Dongyang', 58);
insert into Towns (town_id, name, state_id) values (35, 'Metsamor', 63);
insert into Towns (town_id, name, state_id) values (36, 'Gubukjero Timuk', 79);
insert into Towns (town_id, name, state_id) values (37, 'Wudui', 40);
insert into Towns (town_id, name, state_id) values (38, 'Nar''yan-Mar', 73);
insert into Towns (town_id, name, state_id) values (39, 'Fengxian', 12);
insert into Towns (town_id, name, state_id) values (40, 'Macinhata da Seixa', 101);
insert into Towns (town_id, name, state_id) values (41, 'Balagui', 35);
insert into Towns (town_id, name, state_id) values (42, 'Madrid', 24);
insert into Towns (town_id, name, state_id) values (43, 'Kebili', 157);
insert into Towns (town_id, name, state_id) values (44, 'Tanahmerah', 122);
insert into Towns (town_id, name, state_id) values (45, 'Dodola', 3);
insert into Towns (town_id, name, state_id) values (46, 'Duping', 126);
insert into Towns (town_id, name, state_id) values (47, 'Kovel’', 155);
insert into Towns (town_id, name, state_id) values (48, 'Kuningan', 122);
insert into Towns (town_id, name, state_id) values (49, 'Ndewel', 36);
insert into Towns (town_id, name, state_id) values (50, 'Pasvalys', 3);
insert into Towns (town_id, name, state_id) values (51, 'Linköping', 175);
insert into Towns (town_id, name, state_id) values (52, 'Cianorte', 63);
insert into Towns (town_id, name, state_id) values (53, 'Ibotirama', 156);
insert into Towns (town_id, name, state_id) values (54, 'Bulalacao', 23);
insert into Towns (town_id, name, state_id) values (55, 'Francistown', 162);
insert into Towns (town_id, name, state_id) values (56, 'Aomori Shi', 119);
insert into Towns (town_id, name, state_id) values (57, 'Shkodër', 105);
insert into Towns (town_id, name, state_id) values (58, 'Kuaidamao', 173);
insert into Towns (town_id, name, state_id) values (59, 'Wārāh', 46);
insert into Towns (town_id, name, state_id) values (60, 'Oesena', 116);
insert into Towns (town_id, name, state_id) values (61, 'Jixiang', 155);
insert into Towns (town_id, name, state_id) values (62, 'Aleg', 28);
insert into Towns (town_id, name, state_id) values (63, 'Pisaras', 68);
insert into Towns (town_id, name, state_id) values (64, 'Vitória', 7);
insert into Towns (town_id, name, state_id) values (65, 'Xinzhu', 122);
insert into Towns (town_id, name, state_id) values (66, 'Kesha', 41);
insert into Towns (town_id, name, state_id) values (67, 'Wentugaole', 74);
insert into Towns (town_id, name, state_id) values (68, 'Suvorovo', 183);
insert into Towns (town_id, name, state_id) values (69, 'Tangzi', 197);
insert into Towns (town_id, name, state_id) values (70, 'Baishuiyang', 52);
insert into Towns (town_id, name, state_id) values (71, 'Dijon', 114);
insert into Towns (town_id, name, state_id) values (72, 'Chemal', 34);
insert into Towns (town_id, name, state_id) values (73, 'Muromtsevo', 153);
insert into Towns (town_id, name, state_id) values (74, 'Jāndiāla Sher Khān', 21);
insert into Towns (town_id, name, state_id) values (75, 'Dadian', 122);
insert into Towns (town_id, name, state_id) values (76, 'Vostryakovo', 20);
insert into Towns (town_id, name, state_id) values (77, 'Machetá', 115);
insert into Towns (town_id, name, state_id) values (78, 'Sungailiat', 42);
insert into Towns (town_id, name, state_id) values (79, 'Saint-Sauveur', 105);
insert into Towns (town_id, name, state_id) values (80, 'Fengyan', 80);
insert into Towns (town_id, name, state_id) values (81, 'Yanchi', 103);
insert into Towns (town_id, name, state_id) values (82, 'Nurlat', 92);
insert into Towns (town_id, name, state_id) values (83, 'Arauco', 21);
insert into Towns (town_id, name, state_id) values (84, 'Jacinto Arauz', 4);
insert into Towns (town_id, name, state_id) values (85, 'Pochinki', 57);
insert into Towns (town_id, name, state_id) values (86, 'Anzhero-Sudzhensk', 87);
insert into Towns (town_id, name, state_id) values (87, 'Dalongtan', 152);
insert into Towns (town_id, name, state_id) values (88, 'Austin', 111);
insert into Towns (town_id, name, state_id) values (89, 'Leopoldina', 76);
insert into Towns (town_id, name, state_id) values (90, 'Bulakgebang', 142);
insert into Towns (town_id, name, state_id) values (91, 'Sundbyberg', 175);
insert into Towns (town_id, name, state_id) values (92, 'Al Fujayrah', 54);
insert into Towns (town_id, name, state_id) values (93, 'Faqīrwāli', 122);
insert into Towns (town_id, name, state_id) values (94, 'Al Bahlūlīyah', 50);
insert into Towns (town_id, name, state_id) values (95, 'Santa Cruz del Norte', 50);
insert into Towns (town_id, name, state_id) values (96, 'Changhua', 99);
insert into Towns (town_id, name, state_id) values (97, 'Montecristi', 185);
insert into Towns (town_id, name, state_id) values (98, 'Kristianstad', 16);
insert into Towns (town_id, name, state_id) values (99, 'Khallat Ḩamāmah', 168);
insert into Towns (town_id, name, state_id) values (100, 'Buniaga', 183);
insert into Towns (town_id, name, state_id) values (101, 'Tangkeng', 10);
insert into Towns (town_id, name, state_id) values (102, 'Zhongxiang', 131);
insert into Towns (town_id, name, state_id) values (103, 'Wodzierady', 85);
insert into Towns (town_id, name, state_id) values (104, 'Chigang', 194);
insert into Towns (town_id, name, state_id) values (105, 'Şurmān', 6);
insert into Towns (town_id, name, state_id) values (106, 'Dzików Stary', 108);
insert into Towns (town_id, name, state_id) values (107, 'Shinjō', 131);
insert into Towns (town_id, name, state_id) values (108, 'Ikaalinen', 160);
insert into Towns (town_id, name, state_id) values (109, 'Kharbathā Banī Ḩārith', 7);
insert into Towns (town_id, name, state_id) values (110, 'Ciudad Bolívar', 57);
insert into Towns (town_id, name, state_id) values (111, 'Patrocínio', 84);
insert into Towns (town_id, name, state_id) values (112, 'Sukasirna', 143);
insert into Towns (town_id, name, state_id) values (113, 'Hannover', 159);
insert into Towns (town_id, name, state_id) values (114, 'Papatowai', 177);
insert into Towns (town_id, name, state_id) values (115, 'Vila Velha de Ródão', 122);
insert into Towns (town_id, name, state_id) values (116, 'Yokohama', 134);
insert into Towns (town_id, name, state_id) values (117, 'El Capulin', 182);
insert into Towns (town_id, name, state_id) values (118, 'København', 46);
insert into Towns (town_id, name, state_id) values (119, 'Popil''nya', 77);
insert into Towns (town_id, name, state_id) values (120, 'Piltown', 5);
insert into Towns (town_id, name, state_id) values (121, 'Aku', 195);
insert into Towns (town_id, name, state_id) values (122, 'Shatrovo', 70);
insert into Towns (town_id, name, state_id) values (123, 'Sumbergedong', 14);
insert into Towns (town_id, name, state_id) values (124, 'Wangqu', 145);
insert into Towns (town_id, name, state_id) values (125, 'Paraíso de Chabasquén', 48);
insert into Towns (town_id, name, state_id) values (126, 'Cisantri', 151);
insert into Towns (town_id, name, state_id) values (127, 'Krajan', 190);
insert into Towns (town_id, name, state_id) values (128, 'Ziroudani', 31);
insert into Towns (town_id, name, state_id) values (129, 'Kotakaya Dua', 44);
insert into Towns (town_id, name, state_id) values (130, 'Panjiawan', 198);
insert into Towns (town_id, name, state_id) values (131, 'Quatro Barras', 158);
insert into Towns (town_id, name, state_id) values (132, 'Gryazovets', 70);
insert into Towns (town_id, name, state_id) values (133, 'Chafé', 127);
insert into Towns (town_id, name, state_id) values (134, 'Mangulewa', 184);
insert into Towns (town_id, name, state_id) values (135, 'Honoria', 154);
insert into Towns (town_id, name, state_id) values (136, 'Van Nuys', 185);
insert into Towns (town_id, name, state_id) values (137, 'Magepanda', 176);
insert into Towns (town_id, name, state_id) values (138, 'Nghĩa Hành', 95);
insert into Towns (town_id, name, state_id) values (139, 'Shangtian', 16);
insert into Towns (town_id, name, state_id) values (140, 'Urayasu', 90);
insert into Towns (town_id, name, state_id) values (141, 'Parung', 186);
insert into Towns (town_id, name, state_id) values (142, 'Vanderbijlpark', 45);
insert into Towns (town_id, name, state_id) values (143, 'Changjiang', 16);
insert into Towns (town_id, name, state_id) values (144, 'Thaon-les-Vosges', 35);
insert into Towns (town_id, name, state_id) values (145, 'Xiaotang', 25);
insert into Towns (town_id, name, state_id) values (146, 'Kasli', 130);
insert into Towns (town_id, name, state_id) values (147, 'Lamadelaine', 174);
insert into Towns (town_id, name, state_id) values (148, 'La Cruz de Río Grande', 23);
insert into Towns (town_id, name, state_id) values (149, 'Manay', 120);
insert into Towns (town_id, name, state_id) values (150, 'Tibro', 91);
insert into Towns (town_id, name, state_id) values (151, 'Jalālpur Pīrwāla', 41);
insert into Towns (town_id, name, state_id) values (152, 'Baru', 153);
insert into Towns (town_id, name, state_id) values (153, 'Banqiao', 128);
insert into Towns (town_id, name, state_id) values (154, 'Novovoronezh', 90);
insert into Towns (town_id, name, state_id) values (155, 'Chicago', 132);
insert into Towns (town_id, name, state_id) values (156, 'Sangmélima', 109);
insert into Towns (town_id, name, state_id) values (157, 'Rio Grande', 1);
insert into Towns (town_id, name, state_id) values (158, 'Palma De Mallorca', 194);
insert into Towns (town_id, name, state_id) values (159, 'Içara', 42);
insert into Towns (town_id, name, state_id) values (160, 'Yeping', 129);
insert into Towns (town_id, name, state_id) values (161, 'Loandjili', 130);
insert into Towns (town_id, name, state_id) values (162, 'Rasskazovo', 120);
insert into Towns (town_id, name, state_id) values (163, 'Landskrona', 115);
insert into Towns (town_id, name, state_id) values (164, 'Hucun', 141);
insert into Towns (town_id, name, state_id) values (165, 'Chiri-Yurt', 36);
insert into Towns (town_id, name, state_id) values (166, 'Guadalupe', 183);
insert into Towns (town_id, name, state_id) values (167, 'Simi Valley', 147);
insert into Towns (town_id, name, state_id) values (168, 'Izlake', 64);
insert into Towns (town_id, name, state_id) values (169, 'Montilla', 9);
insert into Towns (town_id, name, state_id) values (170, 'Nueva Fuerza', 110);
insert into Towns (town_id, name, state_id) values (171, 'Charlotte', 91);
insert into Towns (town_id, name, state_id) values (172, 'Uarini', 150);
insert into Towns (town_id, name, state_id) values (173, 'Verkhnyaya Khava', 22);
insert into Towns (town_id, name, state_id) values (174, 'Megati Kelod', 19);
insert into Towns (town_id, name, state_id) values (175, 'Paços', 27);
insert into Towns (town_id, name, state_id) values (176, 'Loreto', 115);
insert into Towns (town_id, name, state_id) values (177, 'Dunmanway', 195);
insert into Towns (town_id, name, state_id) values (178, 'Skien', 65);
insert into Towns (town_id, name, state_id) values (179, 'Czudec', 42);
insert into Towns (town_id, name, state_id) values (180, 'Frösön', 59);
insert into Towns (town_id, name, state_id) values (181, 'Enskededalen', 31);
insert into Towns (town_id, name, state_id) values (182, 'Kraljevo', 165);
insert into Towns (town_id, name, state_id) values (183, 'Xiaohe', 169);
insert into Towns (town_id, name, state_id) values (184, 'Barotac Nuevo', 157);
insert into Towns (town_id, name, state_id) values (185, 'Karasgede', 163);
insert into Towns (town_id, name, state_id) values (186, 'Orichi', 86);
insert into Towns (town_id, name, state_id) values (187, 'Putat Lor', 179);
insert into Towns (town_id, name, state_id) values (188, 'Jāsim', 185);
insert into Towns (town_id, name, state_id) values (189, 'Lesnikovo', 80);
insert into Towns (town_id, name, state_id) values (190, 'Jagodnjak', 119);
insert into Towns (town_id, name, state_id) values (191, 'Kertasari', 127);
insert into Towns (town_id, name, state_id) values (192, 'Abū Tīj', 194);
insert into Towns (town_id, name, state_id) values (193, 'Morales', 136);
insert into Towns (town_id, name, state_id) values (194, 'Mavingouni', 99);
insert into Towns (town_id, name, state_id) values (195, 'Barrosas', 51);
insert into Towns (town_id, name, state_id) values (196, 'Heshui', 16);
insert into Towns (town_id, name, state_id) values (197, 'Tehetu', 100);
insert into Towns (town_id, name, state_id) values (198, 'Santa Cruz de la Sierra', 63);
insert into Towns (town_id, name, state_id) values (199, 'Demuk', 111);
insert into Towns (town_id, name, state_id) values (200, 'Kowala', 3);
insert into Towns (town_id, name, state_id) values (201, 'Zimmi', 67);
insert into Towns (town_id, name, state_id) values (202, 'El Colorado', 145);
insert into Towns (town_id, name, state_id) values (203, 'Ngulahan', 36);
insert into Towns (town_id, name, state_id) values (204, 'Blatnica', 40);
insert into Towns (town_id, name, state_id) values (205, 'Mjamaoué', 132);
insert into Towns (town_id, name, state_id) values (206, 'Kovylkino', 93);
insert into Towns (town_id, name, state_id) values (207, 'Farmahīn', 182);
insert into Towns (town_id, name, state_id) values (208, 'Pianbai', 169);
insert into Towns (town_id, name, state_id) values (209, 'Maevatanana', 28);
insert into Towns (town_id, name, state_id) values (210, 'Tongliao', 178);
insert into Towns (town_id, name, state_id) values (211, 'Tramandaí', 70);
insert into Towns (town_id, name, state_id) values (212, 'Sallins', 100);
insert into Towns (town_id, name, state_id) values (213, 'Trai Ngau', 37);
insert into Towns (town_id, name, state_id) values (214, 'Montecillo', 103);
insert into Towns (town_id, name, state_id) values (215, 'Sake', 51);
insert into Towns (town_id, name, state_id) values (216, 'Pathum Thani', 79);
insert into Towns (town_id, name, state_id) values (217, 'Agen', 17);
insert into Towns (town_id, name, state_id) values (218, 'Sakata', 164);
insert into Towns (town_id, name, state_id) values (219, 'Matlang', 31);
insert into Towns (town_id, name, state_id) values (220, 'Hutou', 33);
insert into Towns (town_id, name, state_id) values (221, 'Sundsvall', 18);
insert into Towns (town_id, name, state_id) values (222, 'Stockholm', 145);
insert into Towns (town_id, name, state_id) values (223, 'Bourg-en-Bresse', 178);
insert into Towns (town_id, name, state_id) values (224, 'Ala', 178);
insert into Towns (town_id, name, state_id) values (225, 'Bokkos', 58);
insert into Towns (town_id, name, state_id) values (226, 'Gimry', 60);
insert into Towns (town_id, name, state_id) values (227, 'Dschang', 70);
insert into Towns (town_id, name, state_id) values (228, 'Hamakita', 108);
insert into Towns (town_id, name, state_id) values (229, 'Muara', 144);
insert into Towns (town_id, name, state_id) values (230, 'Shazhouba', 95);
insert into Towns (town_id, name, state_id) values (231, 'Mojoagung', 174);
insert into Towns (town_id, name, state_id) values (232, 'Tandaltī', 25);
insert into Towns (town_id, name, state_id) values (233, 'Stepanivka', 28);
insert into Towns (town_id, name, state_id) values (234, 'Lučina', 163);
insert into Towns (town_id, name, state_id) values (235, 'Fumin', 153);
insert into Towns (town_id, name, state_id) values (236, 'Miami', 194);
insert into Towns (town_id, name, state_id) values (237, 'Itsukaichi', 29);
insert into Towns (town_id, name, state_id) values (238, 'Yong’an', 142);
insert into Towns (town_id, name, state_id) values (239, 'Xinhe', 54);
insert into Towns (town_id, name, state_id) values (240, 'Petaẖ Tiqwa', 58);
insert into Towns (town_id, name, state_id) values (241, 'Horní Stropnice', 15);
insert into Towns (town_id, name, state_id) values (242, 'Piraí', 94);
insert into Towns (town_id, name, state_id) values (243, 'Ferreira', 180);
insert into Towns (town_id, name, state_id) values (244, 'Cerkvenjak', 67);
insert into Towns (town_id, name, state_id) values (245, 'Krasnaya Polyana', 64);
insert into Towns (town_id, name, state_id) values (246, 'Murzuq', 4);
insert into Towns (town_id, name, state_id) values (247, 'Cimadang', 61);
insert into Towns (town_id, name, state_id) values (248, 'Al Ghandūrah', 190);
insert into Towns (town_id, name, state_id) values (249, 'Burao', 175);
insert into Towns (town_id, name, state_id) values (250, 'Jiancha', 179);
insert into Towns (town_id, name, state_id) values (251, 'Firavitoba', 107);
insert into Towns (town_id, name, state_id) values (252, 'Uritsk', 113);
insert into Towns (town_id, name, state_id) values (253, 'Rezh', 139);
insert into Towns (town_id, name, state_id) values (254, 'Zlechov', 73);
insert into Towns (town_id, name, state_id) values (255, 'Shumikha', 159);
insert into Towns (town_id, name, state_id) values (256, 'Hovås', 103);
insert into Towns (town_id, name, state_id) values (257, 'New Hyde Park', 32);
insert into Towns (town_id, name, state_id) values (258, 'Quỳnh Côi', 112);
insert into Towns (town_id, name, state_id) values (259, 'Tianta', 37);
insert into Towns (town_id, name, state_id) values (260, 'Bodø', 47);
insert into Towns (town_id, name, state_id) values (261, 'Bryukhovetskaya', 134);
insert into Towns (town_id, name, state_id) values (262, 'Nowe Skalmierzyce', 126);
insert into Towns (town_id, name, state_id) values (263, 'Bunia', 185);
insert into Towns (town_id, name, state_id) values (264, 'Bagjasari', 179);
insert into Towns (town_id, name, state_id) values (265, 'Koryčany', 33);
insert into Towns (town_id, name, state_id) values (266, 'Guanqing', 51);
insert into Towns (town_id, name, state_id) values (267, 'Baoxia', 14);
insert into Towns (town_id, name, state_id) values (268, 'El Quetzal', 188);
insert into Towns (town_id, name, state_id) values (269, 'Maracás', 94);
insert into Towns (town_id, name, state_id) values (270, 'Grazhdanskoye', 178);
insert into Towns (town_id, name, state_id) values (271, 'Masis', 83);
insert into Towns (town_id, name, state_id) values (272, 'Wangtai', 169);
insert into Towns (town_id, name, state_id) values (273, 'Kota Kinabalu', 38);
insert into Towns (town_id, name, state_id) values (274, 'Entebbe', 85);
insert into Towns (town_id, name, state_id) values (275, 'Cienfuegos', 45);
insert into Towns (town_id, name, state_id) values (276, 'Hihyā', 34);
insert into Towns (town_id, name, state_id) values (277, 'Dongdong', 114);
insert into Towns (town_id, name, state_id) values (278, 'Cikotok', 105);
insert into Towns (town_id, name, state_id) values (279, 'Lengkongjaya', 111);
insert into Towns (town_id, name, state_id) values (280, 'Su-ngai Kolok', 126);
insert into Towns (town_id, name, state_id) values (281, 'Xinzheng', 108);
insert into Towns (town_id, name, state_id) values (282, 'Konin', 46);
insert into Towns (town_id, name, state_id) values (283, 'Kasama', 171);
insert into Towns (town_id, name, state_id) values (284, 'Sebu', 134);
insert into Towns (town_id, name, state_id) values (285, 'Kedungdoro', 138);
insert into Towns (town_id, name, state_id) values (286, 'Salimbao', 121);
insert into Towns (town_id, name, state_id) values (287, 'Bánica', 28);
insert into Towns (town_id, name, state_id) values (288, 'Biyan', 25);
insert into Towns (town_id, name, state_id) values (289, 'Ōtsuchi', 96);
insert into Towns (town_id, name, state_id) values (290, 'Santo Tomas', 81);
insert into Towns (town_id, name, state_id) values (291, 'Valado dos Frades', 2);
insert into Towns (town_id, name, state_id) values (292, 'Loacan', 160);
insert into Towns (town_id, name, state_id) values (293, 'Phoenix', 16);
insert into Towns (town_id, name, state_id) values (294, 'Nybro', 109);
insert into Towns (town_id, name, state_id) values (295, 'Pasar Kidul', 17);
insert into Towns (town_id, name, state_id) values (296, 'Sergiyev Posad', 21);
insert into Towns (town_id, name, state_id) values (297, 'Yanahuanca', 72);
insert into Towns (town_id, name, state_id) values (298, 'Gia Nghĩa', 109);
insert into Towns (town_id, name, state_id) values (299, 'Nakhon Nayok', 8);
insert into Towns (town_id, name, state_id) values (300, 'Gaotuo', 112);
insert into Towns (town_id, name, state_id) values (301, 'Ponta Grossa', 169);
insert into Towns (town_id, name, state_id) values (302, 'Millet', 163);
insert into Towns (town_id, name, state_id) values (303, 'Patemon', 134);
insert into Towns (town_id, name, state_id) values (304, 'Shezhu', 197);
insert into Towns (town_id, name, state_id) values (305, 'Antsohihy', 41);
insert into Towns (town_id, name, state_id) values (306, 'Liugou', 150);
insert into Towns (town_id, name, state_id) values (307, 'Memória', 163);
insert into Towns (town_id, name, state_id) values (308, 'Sinait', 162);
insert into Towns (town_id, name, state_id) values (309, 'Anxi', 108);
insert into Towns (town_id, name, state_id) values (310, 'Oslo', 178);
insert into Towns (town_id, name, state_id) values (311, 'Kemang', 126);
insert into Towns (town_id, name, state_id) values (312, 'Murowana Goślina', 115);
insert into Towns (town_id, name, state_id) values (313, 'Duobaoshan', 151);
insert into Towns (town_id, name, state_id) values (314, 'Maloyaroslavets', 8);
insert into Towns (town_id, name, state_id) values (315, 'Castro Daire', 131);
insert into Towns (town_id, name, state_id) values (316, 'Donetsk', 13);
insert into Towns (town_id, name, state_id) values (317, 'Blimbing', 2);
insert into Towns (town_id, name, state_id) values (318, 'Gorzkowice', 170);
insert into Towns (town_id, name, state_id) values (319, 'Qingyang', 39);
insert into Towns (town_id, name, state_id) values (320, 'Loboniki', 182);
insert into Towns (town_id, name, state_id) values (321, 'Alabat', 188);
insert into Towns (town_id, name, state_id) values (322, 'Arrah', 23);
insert into Towns (town_id, name, state_id) values (323, 'Thị Trấn Triệu Sơn', 62);
insert into Towns (town_id, name, state_id) values (324, 'Privlaka', 33);
insert into Towns (town_id, name, state_id) values (325, 'Lacabamba', 70);
insert into Towns (town_id, name, state_id) values (326, 'Xinmin', 81);
insert into Towns (town_id, name, state_id) values (327, 'Sanya', 27);
insert into Towns (town_id, name, state_id) values (328, 'Beaconsfield', 178);
insert into Towns (town_id, name, state_id) values (329, 'Hastings', 110);
insert into Towns (town_id, name, state_id) values (330, 'Maruoka', 162);
insert into Towns (town_id, name, state_id) values (331, 'Usu', 153);
insert into Towns (town_id, name, state_id) values (332, 'Rače', 10);
insert into Towns (town_id, name, state_id) values (333, 'Geta', 179);
insert into Towns (town_id, name, state_id) values (334, 'Andapa', 185);
insert into Towns (town_id, name, state_id) values (335, 'Yinglan', 168);
insert into Towns (town_id, name, state_id) values (336, 'Basoko', 88);
insert into Towns (town_id, name, state_id) values (337, 'Vargem Grande Paulista', 154);
insert into Towns (town_id, name, state_id) values (338, 'Al ‘Anān', 8);
insert into Towns (town_id, name, state_id) values (339, 'Knivsta', 166);
insert into Towns (town_id, name, state_id) values (340, 'Ngangpo', 86);
insert into Towns (town_id, name, state_id) values (341, 'Forécariah', 84);
insert into Towns (town_id, name, state_id) values (342, 'Agbor', 10);
insert into Towns (town_id, name, state_id) values (343, 'Tayāsīr', 60);
insert into Towns (town_id, name, state_id) values (344, 'Takub', 96);
insert into Towns (town_id, name, state_id) values (345, 'Pasirlaja', 59);
insert into Towns (town_id, name, state_id) values (346, 'Rekovac', 2);
insert into Towns (town_id, name, state_id) values (347, 'Tsotsin-Yurt', 32);
insert into Towns (town_id, name, state_id) values (348, 'Gucheng', 154);
insert into Towns (town_id, name, state_id) values (349, 'Kavásilas', 31);
insert into Towns (town_id, name, state_id) values (350, 'Butel', 78);
insert into Towns (town_id, name, state_id) values (351, 'Krajan Sumberanget', 113);
insert into Towns (town_id, name, state_id) values (352, 'Satinka', 49);
insert into Towns (town_id, name, state_id) values (353, 'Tianhekou', 186);
insert into Towns (town_id, name, state_id) values (354, 'Mrągowo', 145);
insert into Towns (town_id, name, state_id) values (355, 'Pitangueiras', 88);
insert into Towns (town_id, name, state_id) values (356, 'Senj', 164);
insert into Towns (town_id, name, state_id) values (357, 'Fengli', 50);
insert into Towns (town_id, name, state_id) values (358, 'Steblevë', 130);
insert into Towns (town_id, name, state_id) values (359, 'Berbera', 157);
insert into Towns (town_id, name, state_id) values (360, 'Gīvī', 114);
insert into Towns (town_id, name, state_id) values (361, 'Alibunan', 143);
insert into Towns (town_id, name, state_id) values (362, 'Pavino', 142);
insert into Towns (town_id, name, state_id) values (363, 'New York City', 109);
insert into Towns (town_id, name, state_id) values (364, 'Jastrowie', 72);
insert into Towns (town_id, name, state_id) values (365, 'Borāzjān', 10);
insert into Towns (town_id, name, state_id) values (366, 'São Pedro', 96);
insert into Towns (town_id, name, state_id) values (367, 'Sasa', 162);
insert into Towns (town_id, name, state_id) values (368, 'Debar', 196);
insert into Towns (town_id, name, state_id) values (369, 'Ấp Tân Ngãi', 14);
insert into Towns (town_id, name, state_id) values (370, 'Constance', 138);
insert into Towns (town_id, name, state_id) values (371, 'Boston', 113);
insert into Towns (town_id, name, state_id) values (372, 'Catayauan', 82);
insert into Towns (town_id, name, state_id) values (373, 'Nazaré', 105);
insert into Towns (town_id, name, state_id) values (374, 'Siaya', 130);
insert into Towns (town_id, name, state_id) values (375, 'Guanlu', 66);
insert into Towns (town_id, name, state_id) values (376, 'Pampa del Infierno', 8);
insert into Towns (town_id, name, state_id) values (377, 'Pingshan', 119);
insert into Towns (town_id, name, state_id) values (378, 'Toungo', 10);
insert into Towns (town_id, name, state_id) values (379, 'Nocaima', 154);
insert into Towns (town_id, name, state_id) values (380, 'Ambalavao', 194);
insert into Towns (town_id, name, state_id) values (381, 'Radenković', 198);
insert into Towns (town_id, name, state_id) values (382, 'Nesebar', 74);
insert into Towns (town_id, name, state_id) values (383, 'Chengshan', 8);
insert into Towns (town_id, name, state_id) values (384, 'Mirecourt', 171);
insert into Towns (town_id, name, state_id) values (385, 'Lelydorp', 132);
insert into Towns (town_id, name, state_id) values (386, 'Paris 10', 153);
insert into Towns (town_id, name, state_id) values (387, 'Shaping', 198);
insert into Towns (town_id, name, state_id) values (388, 'Jiabeiyan', 124);
insert into Towns (town_id, name, state_id) values (389, 'Daqiao', 34);
insert into Towns (town_id, name, state_id) values (390, 'Jisegumen', 13);
insert into Towns (town_id, name, state_id) values (391, 'Xiabeisi', 129);
insert into Towns (town_id, name, state_id) values (392, 'Hausjärvi', 32);
insert into Towns (town_id, name, state_id) values (393, 'Dakhla', 135);
insert into Towns (town_id, name, state_id) values (394, 'Turgenevo', 125);
insert into Towns (town_id, name, state_id) values (395, 'Angkup', 159);
insert into Towns (town_id, name, state_id) values (396, 'Changning', 41);
insert into Towns (town_id, name, state_id) values (397, 'Serrana', 39);
insert into Towns (town_id, name, state_id) values (398, 'Rio Claro', 85);
insert into Towns (town_id, name, state_id) values (399, 'Koror', 156);
insert into Towns (town_id, name, state_id) values (400, 'Dundbürd', 152);
insert into Towns (town_id, name, state_id) values (401, 'Dubrovnik', 93);
insert into Towns (town_id, name, state_id) values (402, 'Chafé', 181);
insert into Towns (town_id, name, state_id) values (403, 'Nogueira', 112);
insert into Towns (town_id, name, state_id) values (404, 'Kemendung', 163);
insert into Towns (town_id, name, state_id) values (405, 'Sakai', 8);
insert into Towns (town_id, name, state_id) values (406, 'Niños Heroes', 131);
insert into Towns (town_id, name, state_id) values (407, 'Ol’gino', 19);
insert into Towns (town_id, name, state_id) values (408, 'Caldono', 159);
insert into Towns (town_id, name, state_id) values (409, 'Lipa City', 62);
insert into Towns (town_id, name, state_id) values (410, 'Adolfo Lopez Mateos', 142);
insert into Towns (town_id, name, state_id) values (411, 'Karlskrona', 151);
insert into Towns (town_id, name, state_id) values (412, 'Boyany', 55);
insert into Towns (town_id, name, state_id) values (413, 'Pomerode', 84);
insert into Towns (town_id, name, state_id) values (414, 'Shakhty', 157);
insert into Towns (town_id, name, state_id) values (415, 'Ruse', 44);
insert into Towns (town_id, name, state_id) values (416, 'Sancti Spíritus', 183);
insert into Towns (town_id, name, state_id) values (417, 'Huxi', 144);
insert into Towns (town_id, name, state_id) values (418, 'Parigi', 126);
insert into Towns (town_id, name, state_id) values (419, 'Catalão', 167);
insert into Towns (town_id, name, state_id) values (420, 'Bezons', 149);
insert into Towns (town_id, name, state_id) values (421, 'Pagak', 103);
insert into Towns (town_id, name, state_id) values (422, 'Grzechynia', 104);
insert into Towns (town_id, name, state_id) values (423, 'Shawnee Mission', 174);
insert into Towns (town_id, name, state_id) values (424, 'Talisayan', 72);
insert into Towns (town_id, name, state_id) values (425, 'Zhongluotan', 100);
insert into Towns (town_id, name, state_id) values (426, 'Purda', 52);
insert into Towns (town_id, name, state_id) values (427, 'Dugu', 147);
insert into Towns (town_id, name, state_id) values (428, 'Zaliztsi', 59);
insert into Towns (town_id, name, state_id) values (429, 'Huxi', 192);
insert into Towns (town_id, name, state_id) values (430, 'Orvault', 53);
insert into Towns (town_id, name, state_id) values (431, 'Mnichovo Hradiště', 3);
insert into Towns (town_id, name, state_id) values (432, 'Banshu', 77);
insert into Towns (town_id, name, state_id) values (433, 'Arão', 69);
insert into Towns (town_id, name, state_id) values (434, 'Qiaosi', 57);
insert into Towns (town_id, name, state_id) values (435, 'Bago', 5);
insert into Towns (town_id, name, state_id) values (436, 'Greda', 8);
insert into Towns (town_id, name, state_id) values (437, 'Trieste', 164);
insert into Towns (town_id, name, state_id) values (438, 'Vicente Guerrero', 126);
insert into Towns (town_id, name, state_id) values (439, 'Ambulong', 108);
insert into Towns (town_id, name, state_id) values (440, 'Ouijjane', 37);
insert into Towns (town_id, name, state_id) values (441, 'Yonggu', 170);
insert into Towns (town_id, name, state_id) values (442, 'Misheronskiy', 168);
insert into Towns (town_id, name, state_id) values (443, 'Qutqashen', 124);
insert into Towns (town_id, name, state_id) values (444, 'Xinhui', 144);
insert into Towns (town_id, name, state_id) values (445, 'Liucheng', 175);
insert into Towns (town_id, name, state_id) values (446, 'Wairinding', 154);
insert into Towns (town_id, name, state_id) values (447, 'Yingpu', 74);
insert into Towns (town_id, name, state_id) values (448, 'Qingminghe', 60);
insert into Towns (town_id, name, state_id) values (449, 'Alurbulu', 5);
insert into Towns (town_id, name, state_id) values (450, 'Atalaia', 23);
insert into Towns (town_id, name, state_id) values (451, 'Huazhaizi', 17);
insert into Towns (town_id, name, state_id) values (452, 'Tacurong', 118);
insert into Towns (town_id, name, state_id) values (453, 'Sioguí Abajo', 160);
insert into Towns (town_id, name, state_id) values (454, 'Waso', 82);
insert into Towns (town_id, name, state_id) values (455, 'les Escaldes', 169);
insert into Towns (town_id, name, state_id) values (456, 'Pengchang', 89);
insert into Towns (town_id, name, state_id) values (457, 'Razgrad', 122);
insert into Towns (town_id, name, state_id) values (458, 'Altuf’yevskiy', 200);
insert into Towns (town_id, name, state_id) values (459, 'Pyinmana', 175);
insert into Towns (town_id, name, state_id) values (460, 'Gobō', 71);
insert into Towns (town_id, name, state_id) values (461, 'Parczew', 132);
insert into Towns (town_id, name, state_id) values (462, 'Langob', 67);
insert into Towns (town_id, name, state_id) values (463, 'Cilebang Satu', 143);
insert into Towns (town_id, name, state_id) values (464, 'Maredakamau', 148);
insert into Towns (town_id, name, state_id) values (465, 'Jiangkouxu', 141);
insert into Towns (town_id, name, state_id) values (466, 'Mapaniqui', 180);
insert into Towns (town_id, name, state_id) values (467, 'Kidangbang', 144);
insert into Towns (town_id, name, state_id) values (468, 'Krasnokholmskiy', 12);
insert into Towns (town_id, name, state_id) values (469, 'Jixiang', 132);
insert into Towns (town_id, name, state_id) values (470, 'Mugi', 131);
insert into Towns (town_id, name, state_id) values (471, 'Newlands', 179);
insert into Towns (town_id, name, state_id) values (472, 'Tānsen', 168);
insert into Towns (town_id, name, state_id) values (473, 'Baisha', 41);
insert into Towns (town_id, name, state_id) values (474, 'Memphis', 196);
insert into Towns (town_id, name, state_id) values (475, 'Nanterre', 42);
insert into Towns (town_id, name, state_id) values (476, 'Paris 05', 83);
insert into Towns (town_id, name, state_id) values (477, 'Touzao', 92);
insert into Towns (town_id, name, state_id) values (478, 'Pedreira', 94);
insert into Towns (town_id, name, state_id) values (479, 'San Benito', 151);
insert into Towns (town_id, name, state_id) values (480, 'Olutanga', 83);
insert into Towns (town_id, name, state_id) values (481, 'Hanting', 198);
insert into Towns (town_id, name, state_id) values (482, 'Nanyi', 62);
insert into Towns (town_id, name, state_id) values (483, 'Feteira Grande', 79);
insert into Towns (town_id, name, state_id) values (484, 'Yangqiao', 28);
insert into Towns (town_id, name, state_id) values (485, 'Joaquín V. González', 87);
insert into Towns (town_id, name, state_id) values (486, 'Pasadena', 175);
insert into Towns (town_id, name, state_id) values (487, 'Mulhouse', 112);
insert into Towns (town_id, name, state_id) values (488, 'Salaspils', 35);
insert into Towns (town_id, name, state_id) values (489, 'Figueiredo', 123);
insert into Towns (town_id, name, state_id) values (490, 'Bazzāryah', 2);
insert into Towns (town_id, name, state_id) values (491, 'Areado', 190);
insert into Towns (town_id, name, state_id) values (492, 'Al Ḩaffah', 164);
insert into Towns (town_id, name, state_id) values (493, 'Islāmkot', 15);
insert into Towns (town_id, name, state_id) values (494, 'Xinkaikou', 193);
insert into Towns (town_id, name, state_id) values (495, 'Enewetak', 178);
insert into Towns (town_id, name, state_id) values (496, 'Dongbatu', 175);
insert into Towns (town_id, name, state_id) values (497, 'Trà My', 6);
insert into Towns (town_id, name, state_id) values (498, 'La Sierpe', 153);
insert into Towns (town_id, name, state_id) values (499, 'Dongsheng', 101);
insert into Towns (town_id, name, state_id) values (500, 'Sanshengyuan', 95);
